# Generated by Django 5.1.4 on 2026-08-16 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.company'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.role'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserCompany', to='organization.company'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_0c9f12_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['company', 'is_active'], name='accounts_us_company_184fc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercompany',
            unique_together={('user', 'company')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uid'], name='accounts_us_uid_0fe54b_idx'),
        ),
    ]
